# Generated by Django 3.2.12 on 2022-03-14 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(db_column='taks_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task.task', verbose_name='task_id'),
        ),
    ]
