# Generated by Django 3.2.12 on 2022-03-14 14:54

import django.core.validators
from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220314_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='B', max_length=2, validators=[task.models.Task.priority_validator]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='init', max_length=20, validators=[task.models.Task.status_validator]),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='progress_flag',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
